### ISSUE TITLE
melodic-devel branch fails to build on Ubuntu 18.04/Melodic + PCL 1.9 with to ConvexHull error

### ISSUE THREAD

**Issue by patbenatar** [ros-perception/perception_pcl#242]
Trying to use `catkin build` to compile the `melodic-devel` branch on a Jetson Xavier with Ubuntu 18.04/Melodic + PCL 1.9 installed. I've traced this down to what I think is an issue related to qhull and an `#ifdef HAVE_QHULL` in `convex_hull.h` inside PCL, however I've confirmed that `libqhull-dev` is installed on the device...

```
In file included from /home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/src/pcl_ros/surface/convex_hull.cpp:40:0:
/home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/include/pcl_ros/surface/convex_hull.h:79:12: error: ‘ConvexHull’ in namespace ‘pcl’ does not name a template type
       pcl::ConvexHull<pcl::PointXYZ> impl_;
            ^~~~~~~~~~
/home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/src/pcl_ros/surface/convex_hull.cpp: In member function ‘void pcl_ros::ConvexHull2D::input_indices_callback(const PointCloudConstPtr&, const PointIndicesConstPtr&)’:
/home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/src/pcl_ros/surface/convex_hull.cpp:154:3: error: ‘impl_’ was not declared in this scope
   impl_.setInputCloud (cloud);
   ^~~~~
/home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/src/pcl_ros/surface/moving_least_squares.cpp: In member function ‘void pcl_ros::MovingLeastSquares::config_callback(pcl_ros::MLSConfig&, uint32_t)’:
/home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/src/pcl_ros/surface/moving_least_squares.cpp:216:48: warning: ‘void pcl::MovingLeastSquares<PointInT, PointOutT>::setPolynomialFit(bool) [with PointInT = pcl::PointXYZ; PointOutT = pcl::PointNormal]’ is deprecated: [pcl::surface::MovingLeastSquares::setPolynomialFit] setPolynomialFit is deprecated. Please use setPolynomialOrder instead. [-Wdeprecated-declarations]
     impl_.setPolynomialFit (use_polynomial_fit_);
                                                ^
In file included from /home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/include/pcl_ros/surface/moving_least_squares.h:44:0,
                 from /home/nvidia/catkin_ws/src/perception_pcl/pcl_ros/src/pcl_ros/surface/moving_least_squares.cpp:39:
/usr/local/include/pcl-1.9/pcl/surface/mls.h:362:7: note: declared here
       setPolynomialFit (bool polynomial_fit)
       ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/pcl_ros_surface.dir/src/pcl_ros/surface/convex_hull.cpp.o] Error 1
```

**Comment by mvieth** [comment]
Is this still an issue?
If yes, you could try [this tutorial](http://www.pointclouds.org/documentation/tutorials/hull_2d.php) (switch out the `ConcaveHull` for `ConvexHull`). If the same error appears, the problem is with PCL itself and you should create an issue there.
It would also be interesting to know how you installed PCL. Since the apt-version for 18.04 is 1.8.1 and not 1.9, you probably compiled it yourself? Maybe some misconfiguration happened there?

**Comment by patbenatar** [comment]
@mvieth I can't confirm if this is still an issue, as I left it off with a workaround and haven't gotten around to trying other solutions since then. We were compiling PCL from source, so given that I'd be OK with closing out this issue and considering it an edge case or an issue unrelated to this repository. Cheers :beers:

**Comment by doctorcolossus** [comment]
I am getting this error with the following Dockerfile. I had to compile PCL from source, since `elevation_mapping` depends on some macro introduced in 1.11 and the apt version for Ubuntu 20.04 is 1.10.

```
FROM ros:melodic-ros-base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install \
      --yes \
      --no-install-recommends \
      git \
      libeigen3-dev \
      libqhull-dev \
      libusb-1.0-0-dev \
      libvtk7-dev \
      libvtk7-jni \
      python3-catkin-tools \
      qtbase5-dev \
      ros-$ROS_DISTRO-eigen-conversions \
      ros-$ROS_DISTRO-gazebo-ros \
      ros-$ROS_DISTRO-grid-map \
      ros-$ROS_DISTRO-pcl-msgs \
      ros-$ROS_DISTRO-tf-conversions \
      ros-$ROS_DISTRO-tf2-eigen \
      ros-$ROS_DISTRO-turtlebot3-description \
      ros-$ROS_DISTRO-turtlebot3-gazebo \
      wget && \
    apt-get clean

RUN wget https://github.com/PointCloudLibrary/pcl/archive/refs/tags/pcl-1.14.0.tar.gz && \
    tar xvf pcl-1.14.0.tar.gz && \
    rm pcl-1.14.0.tar.gz && \
    cd pcl-pcl-1.14.0 && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make -j2 && \
    make -j2 install && \
    cd ../.. && \
    rm -r pcl-pcl-1.14.0

ARG VTK_DIR=/usr/lib/cmake/vtk-7.1

RUN mkdir -p /catkin_ws/src && \
    cd /catkin_ws/src && \
    git clone https://github.com/anybotics/kindr && \
    git clone https://github.com/anybotics/kindr_ros && \
    git clone https://github.com/anybotics/elevation_mapping && \
    git clone https://github.com/anybotics/message_logger && \
    wget https://github.com/ros-perception/perception_pcl/archive/refs/tags/1.7.4.tar.gz && \
    ls && \
    tar xvf 1.7.4.tar.gz && \
    rm 1.7.4.tar.gz && \
    cd /catkin_ws && \
    . /opt/ros/$ROS_DISTRO/setup.sh && \
    catkin init && \
    catkin build
```

```
Errors << pcl_ros:make /catkin_ws/logs/pcl_ros/build.make.000.log              
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/feature.cpp:50:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/feature.h:42:10: fatal error: pcl/features/feature.h: No such file or directory
 #include <pcl/features/feature.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/feature.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/shot_omp.cpp:38:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/shot_omp.h:40:10: fatal error: pcl/features/shot_omp.h: No such file or directory
 #include <pcl/features/shot_omp.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/shot_omp.cpp.o] Error 1
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/boundary.cpp:39:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/boundary.h:43:10: fatal error: pcl/features/boundary.h: No such file or directory
 #include <pcl/features/boundary.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/shot.cpp:38:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/shot.h:40:10: fatal error: pcl/features/shot.h: No such file or directory
 #include <pcl/features/shot.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/boundary.cpp.o] Error 1
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/shot.cpp.o] Error 1
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/fpfh.cpp:39:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/fpfh.h:41:10: fatal error: pcl/features/fpfh.h: No such file or directory
 #include <pcl/features/fpfh.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/fpfh.cpp.o] Error 1
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/moment_invariants.cpp:39:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/moment_invariants.h:41:10: fatal error: pcl/features/moment_invariants.h: No such file or directory
 #include <pcl/features/moment_invariants.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/moment_invariants.cpp.o] Error 1
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/features/fpfh_omp.cpp:39:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/features/fpfh_omp.h:41:10: fatal error: pcl/features/fpfh_omp.h: No such file or directory
 #include <pcl/features/fpfh_omp.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_features.dir/src/pcl_ros/features/fpfh_omp.cpp.o] Error 1
make[1]: *** [CMakeFiles/pcl_ros_features.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/surface/moving_least_squares.cpp:39:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/surface/moving_least_squares.h:44:10: fatal error: pcl/surface/mls.h: No such file or directory
 #include <pcl/surface/mls.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /catkin_ws/src/perception_pcl-1.7.4/pcl_ros/src/pcl_ros/surface/convex_hull.cpp:39:0:
/catkin_ws/src/perception_pcl-1.7.4/pcl_ros/include/pcl_ros/surface/convex_hull.h:44:10: fatal error: pcl/surface/convex_hull.h: No such file or directory
 #include <pcl/surface/convex_hull.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_surface.dir/src/pcl_ros/surface/moving_least_squares.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/pcl_ros_surface.dir/src/pcl_ros/surface/convex_hull.cpp.o] Error 1
make[1]: *** [CMakeFiles/pcl_ros_surface.dir/all] Error 2
make: *** [all] Error 2
cd /catkin_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/make --jobserver-fds=3,4 -j; cd -

...............................................................................
Failed << pcl_ros:make                                            [ Exited with code 2 ]
```
