### ISSUE TITLE
pcl_ros shows compilation error with PCL 1.8

### ISSUE THREAD

**Issue by SubMishMar** [ros-perception/perception_pcl#262]
I have pcl 1.8 installed and I get errors like:
`CMake Error at /opt/ros/kinetic/share/pcl_ros/cmake/pcl_rosConfig.cmake:113 (message):
  Project 'pcl_ros' specifies '/usr/include/pcl-1.7' as an include dir, which
  is not found. `
When trying to catkin build. How can change the include folder that pcl_ros is looking for by replacing pcl-1.7 with pcl-1.8?

**Comment by SteveMacenski** [comment]
Supported version is https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021 if you are working with pcl-1.8 on Kinetic, you will need to modify some files. The melodic branch should work with 1.8.1.
