### ISSUE TITLE
Build Failed with Melodic

### ISSUE THREAD

**Issue by NicoBrug** [ros-perception/perception_pcl#272]
When i make "catkin_make" i see this error : 
`make[2]: *** [perception_pcl/pcl_ros/CMakeFiles/pcl_ros_filters.dir/src/pcl_ros/filters/voxel_grid.cpp.o] Error 1
CMakeFiles/Makefile2:12997: recipe for target 'perception_pcl/pcl_ros/CMakeFiles/pcl_ros_filters.dir/all' failed
make[1]: *** [perception_pcl/pcl_ros/CMakeFiles/pcl_ros_filters.dir/all] Error 2
Makefile:140: recipe for target 'all' failed`

I see the class VoxelGridConfig has no member named "min_points_per_voxel". I verified in the voxel_grid.h and effectively, the class don't have this member. 
 I work on ubuntu 18.04 and melodic.

**Comment by SteveMacenski** [comment]
I see it [here](https://github.com/ros-perception/perception_pcl/blob/601d980801c53913f5982dbecd16b303aba0158e/pcl_ros/cfg/VoxelGrid.cfg#L16) and [here](https://github.com/ros-perception/perception_pcl/blob/2f70209fb51ec7202e4d318437d12bdd85b3183c/pcl_ros/src/pcl_ros/filters/voxel_grid.cpp#L86). Where do you think its missing from? 

Are you sure you've pulled in changes in the last ~6 months to melodic devel?

I just built it with melodic binaries without an issue. Maybe catkin clean and catkin build again? Perhaps there's something caching incorrectly.
